<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Twitter Proj</title>
    <link rel="shortcut icon" href="images/favicon.ico" type="image/x-icon">

    <script
      src="https://code.jquery.com/jquery-3.5.1.slim.js"
      integrity="sha256-DrT5NfxfbHvMHux31Lkhxg42LY6of8TaYyK50jnxRnM="
      crossorigin="anonymous"
    ></script>

    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
    />

    <link rel="preconnect" href="https://fonts.gstatic.com" />
    <link
      href="https://fonts.googleapis.com/css2?family=Nunito:wght@400;600;700;800&display=swap"
      rel="stylesheet"
    />

    <link rel="stylesheet" href="/styles/main.css" />
    <link rel="stylesheet" href="/styles/partials/index.css" />
    <link rel="stylesheet" href="/styles/partials/inputs.css" />
    <link rel="stylesheet" href="/styles/partials/signup.css" />
    <link rel="stylesheet" href="/styles/partials/login.css" />
    <link rel="stylesheet" href="/styles/partials/success.css" />
    <link rel="stylesheet" href="/styles/partials/home.css">
    <link rel="stylesheet" href="/styles/partials/explore.css">
  </head>

  <body>
    <div id="container">
      <? $this->content() ?>
    </div>

  </body>
</html>
