<div class="page-signup">
  <main>
    <div class="card-signup">
      <div class="twitter-logo">
        <i class="fa fa-twitter"></i>
      </div>
      <h1>Criar sua conta</h1>

      <? if ($this->view->error_info['invalidRegisters']) { ?>
      <small class='text-warning'>Erro preencha os campos corretamente.</small>
      <? } ?>

      <form action="/register" method='POST' id='registerform'>
        <div class="input-block">
          <input type="text" name="name" id="name" value="<?= $this->view->user_info['name'] ?>">
          <label for=" name">Nome</label>
        </div>

        <div class="input-block">
          <input type="text" name="username" id="username" value="<?= $this->view->user_info['username'] ?>">
          <label for="username">Nome de usuário</label>
          <? if ($this->view->error_info['invalidUsername']) { ?>
          <small class=' text-warning'>Nome de usuário já existente.</small>
          <? } ?>
        </div>


        <div class="input-block">
          <input type="text" name="email" id="email" value="<?= $this->view->user_info['email'] ?>">
          <label for="email">E-mail</label>
          <? if ($this->view->error_info['invalidEmail']) { ?>
          <small class='text-warning'>E-mail já cadastrado.</small>
          <? } ?>
        </div>


        <div class="input-block">
          <input type="password" name="password" id="password" value="<?= $this->view->user_info['password'] ?>">
          <label for="password">Senha</label>
        </div>

        <p class='info-warning'>
          Ao inscrever-se, você concorda com os Termos de Serviços e com as Políticas de Privacidade,
          incluindo o Uso de Cookies. Outras pessoas poderão encontrar você pelo e-mail ou número de
          telefone fornecido.
        </p>

        <button type='submit' form='registerform' class='btn btn-primary signup-button'>Inscrever-se</button>
      </form>
    </div>
  </main>
</div>